version: '3.6'

volumes:
  pg_db:

services:
  tinkoff_bot:
    container_name: tinkoff_bot
    restart: no
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./src:/usr/src/tinkoff_bot/src
    working_dir: /usr/src/tinkoff_usd_tg_bot/
    depends_on:
      - tinkoff_bot_pg_db


  tinkoff_bot_pg_db:
    container_name: tinkoff_bot_pg_db
    image: postgres:13.3
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - pg_db:/var/lib/postgresql/data
    working_dir: /var/lib/postgresql/data
    ports:
      - "5434:5432"